[package]
name = "opencl-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
egui = "0.22.0"
egui_extras = "0.22.0"
epaint = "0.22.0"
ocl = "0.19.4"
ocl-core = "0.11.3"
