[package]
name = "opencl-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.23.0"
egui = "0.23.0"
epaint = "0.23.0"
ocl = "0.19.5"
egui_inspect = { git = "https://github.com/dmirauta/egui_inspect" }
